#!/bin/bash

###
#
# Script for dumping MongoDB and Postgres databases as backup.
#
###

DBNAME=$(cat ../../.dbname | python -c 'import sys, json; print json.load(sys.stdin)["dbname"]')
mongodump -d $DBNAME -o ../db-dumps/mongodump
pg_dump -d $DBNAME > ../db-dumps/psqldump
